### ISSUE TITLE
Homebrew missing mmd* scripts

### ISSUE THREAD

**Issue by iandol** [fletcher/MultiMarkdown-5#1]
Thanks for the new V5. As a user of homebrew to install MMD, I notice that the new V5 does not include the mmd* scripts by default, and there is no option to install it. I know that it is *not your responsibility* to maintain the brew file to install mmd, but just wondered if you had any tips on how to update the brew file so that the scripts could be installed? I assume this is related to your change to the Mac installer?

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/multimarkdown.rb

I also assume as you've switched from make that building with that brew will break too?

**Comment by iandol** [comment]
Just to clarify, by default brew installs and update via bottles, which are pre-compiled binaries. And I see the make instructions are updated in the brew so should work with cmake.

**Comment by fletcher** [comment]
I am not a homebrew expert.  That said it looks like a lot of things were done right with this formula for 5.0.

The changes I would look at considering:

* Perhaps the `head` modifier should point to the develop branch?  The master branch will only be used for official releases.  The develop branch will include changes that are uploaded prior to the next release.
* Does `bin.install "multimarkdown"` mean to only install the multimarkdown binary?  Would something different need to be done to also install the scripts?  The `make install` command for the default system *should* include the scripts, but I don't remember whether I've tested that or not.
* In any case, the scripts are not dependent on certain versions of MMD.  If you install them once, you really never need to worry about them again.  The changes that have been made since they were first released have been rather minimal and tend to fix things on "edge case" operating systems.  The functionality on OS X really hasn't changed in years.
* Change `Multimarkdown` to the proper `MultiMarkdown`.  :)
* The "conflicts_with" markers only make sense if the scripts are being installed.  Otherwise there are no conflicts.

**Comment by iandol** [comment]
Here is the homebrew issue, will close this here: https://github.com/Homebrew/homebrew/issues/46629
