### ISSUE TITLE
Syntax for comments

### ISSUE THREAD

**Issue by olivierkes** [fletcher/MultiMarkdown-5#12]
Hi,
I was wondering if you were open to add a syntax for comments. Comments would be totally ignored by parser. I'm using txt2tags, and i'm so much used to them that it seems difficult to switch to mmd because of that.
I know that right know we can use html comments, but it's not very convenient, and they would appear in html source.
A simple syntax could be "% " or "# " at the beginning of a line.
Regards,

**Comment by fletcher** [comment]
CriticMarkup already provides a syntax for comments:

	{>>This is a comment<<}


http://fletcher.github.io/MultiMarkdown-5/criticmarkup.html


Fletcher

On 3/4/16 1:16 PM, Olivier wrote:
> Hi,
> I was wondering if you were open to add a syntax for comments. Comments
> would be totally ignored by parser. I'm using txt2tags, and i'm so much
> used to them that it seems difficult to switch to mmd because of that.
> I know that right know we can use html comments, but it's not very
> convenient, and they would appear in html source.
> A simple syntax could be "% " or "# " at the beginning of a line.
> Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fletcher/MultiMarkdown-5/issues/12>.
>

-- 
Fletcher T. Penney
fletcher@fletcherpenney.net

**Comment by olivierkes** [comment]
Not the most convenient syntax to simply comment out a whole line or paragraph, but will do.

**Comment by jlrn7** [comment]
If you preprocess your input file with [gpp](http://en.nothingisreal.com/wiki/GPP), as explained by [random determinism](http://bit.ly/1UTmU9o) you can define your comments any way you like, among other things...

**Comment by ickc** [comment]
Under the current mmd syntax, if you want to avoid using CriticsMarkup to comment (because one want to separate coding comment and editing comment), you can do something like:

```
<!--
    \begin{comment}
        [COMMENT GOES HERE]
    \end{comment}
-->
```

Because HTML comments are ignored except in LaTeX output (according to the documentation), so using an extra LaTeX comment will guarantee it is a comment in all output formats.

The same tricks can be applied to more complicated situation, like this:

```
<!-- \begin{comment} -->
{{TOC}}
<!-- \end{comment} -->
```

which I included in almost all my mmd files, because I want the LaTeX generated TOC when the output is LaTeX, and otherwise let MMD do the work for me (seems like the obvious and reasonable expectation from TOC feature, and is the default behavior in pandoc with `--toc` args. But in MMD this is the workaround.)

**Comment by pischky** [comment]
In version 6.4.0 this workd for me when I need to comment out multiple lines:
```
<div style="display: none">
bla bla 
</div>
```

The source is included in HTML.
