### ISSUE TITLE
Suggestion: New Levels of Emphasis by Using Small Caps

### ISSUE THREAD

**Issue by ickc** [fletcher/MultiMarkdown-5#13]
I suggest a new level of emphasis like this `****small cap****`

The old tricks would work because of how binary works (italic as "1st digit" emphasis, bold as "2nd digit" emphasis, small caps as "3rd digit" emphasis):
1. `*italic*`
2. `**bold**`
3. `***bold and italic***`
4. `****small cap****`
5. `*****small cap and italic*****`
6. `******small cap and bold******`
7. `*******small cap and bold and italic*******`

The inspiration is that people uses all caps all the time to maximally emphasize things, especially in plain text. Considering all italic, bold, small caps are different font variants, all used in different levels in emphasis. And then all caps could be viewed as a lazy form of small caps, as sometimes it is the only way to write (e.g. ASCII). Small caps seems to be the typographically more correct way instead of all caps.

By the way, I am not saying all 7 levels should be used, but there's a unambiguous decomposition of a combination of all 3 types of emphasis. The end user can decide which combinations to be used.

In terms of output, there's a way to denote all caps in both LaTeX and HTML. I'm not sure about ODF but probably there is. Lastly, for OPML, if it can't be done, it could be fake by all caps.

Related to my suggestion in jgm/pandoc#2761

Lastly, I have an account using the name "Kolen" in your MultiMarkdown support page. But since I'm suggesting new syntax so it seems to me here is a better location to discuss this. But let me know if you prefer me to go to MultiMarkdown support page and added a 'suggestion' there.

**Comment by fletcher** [comment]
This github page is fine, or you can use the support page:  <http://support.fletcherpenney.net/>  


I skimmed through the discussion at the pandoc project.  I am not convinced this is a good idea to implement for all users.  I will leave the issue open for further discussion, and if there is meaningful new discussion on the pandoc page, let me know (I don't monitor those issues regularly).

Just because I don't add this to MultiMarkdown "proper" doesn't mean you can't add it to your own private copy so that you can use it.  That's the beauty of open source projects!

Whether I implement them or not, I do honestly appreciate getting suggestions.  Thank you!!

**Comment by ickc** [comment]
Thanks for considering it anyway. My suggestion seems very natural *to me*. But telling others seems to reflect that is not a good idea (although I still believe in it).

Capability aside (I learnt C++ 10 years ago and never practiced in the meanwhile), I don't like to create my own forked version of any software. If it is a great idea, every people should share it, if it isn't, I shouldn't use it. (because I hate fragmentation, compatibility, issue, etc. which is by the way what Markdown is experiencing right now...)

Lastly, this is how I currently use small caps in MMD (with HTML and LaTeX output in mind), in case people might find it useful:

```html
<!-- \textsc{ --><span style="font-variant: small-caps;">
{{Small Caps texts...}}
<!-- } --></span>
```
