### ISSUE TITLE
_: and :_ prevent output of <em> and/or <strong>

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-5#20]
Tested with version 5.2.0, commit 5d9a834.

Input:
```
_Test_:

__Test__:

___Test___:
```
Output:
```
<p>_Test_:</p>

<p>__Test__:</p>

<p>___Test___:</p>
```
Although probably nobody would write like this, I'm also not sure if this is correct, input:

```
Is :_this_ or :__this__ or :___this___ correct?
```
Output
```
<p>Is :_this_ or :__this__ or :___this___ correct?</p>
```

Putting a space between `_`and `:` produces `em` and `strong` tags. Is this behaviour intended?

**Comment by fletcher** [comment]
This will be fixed in the next develop commit(s) -- working on fixing some edge cases and improving performance in the emph/strong parser.

Thanks!

**Comment by fletcher** [comment]
The first examples now work properly in the development branch, and will work in 5.3.

The last example is currently "correct" for MMD (e.g. it is treated as intraword emphasis, which is disabled for underscores), but will be handled differently in the next version of MMD (MMD 6).  MMD 6 will have an entirely new parser, so I can make some of this behavior more consistent without some of the workarounds the PEG would require. 

If you want the last example to work, use `*` instead of `_` for MMD 5.
