### ISSUE TITLE
Underscore or asterisk at the end of a link renders as <em>

### ISSUE THREAD

**Issue by nloveladyallen** [fletcher/MultiMarkdown-5#25]
Input:

    [foo_](http://example.com/bar_)
    [foo*](http://example.com/bar*)

Expected output:

    <p><a href="http://example.com/bar_">foo_</a></p>
    <p><a href="http://example.com/bar*">foo*</a></p>

[foo_](http://example.com/bar_)
[foo*](http://example.com/bar*)

Real output:

     <p>[foo<em>](http://example.com/bar</em>)</p>
     <p>[foo<em>](http://example.com/bar</em>)</p>

\[foo*](http://example.com/bar*)
\[foo*](http://example.com/bar*)

**Comment by fletcher** [comment]
I'm working on MMD 6 -- this is an entirely new, from scratch, rewrite designed to dramatically improve performance.  One of the motivations was to come up with an accurate emph/strong parser that also improves performance.

For now, you can escape characters so that this doesn't happen, e.g. `[foo\_]`.
