### ISSUE TITLE
mmd2tex Translating to wrong beginning smart quote on multi-paragraph dialogue

### ISSUE THREAD

**Issue by firstclown** [fletcher/MultiMarkdown-5#28]
When translating a multi-paragraph dialogue like this:

    "Hi, Martin. Nice suit.

    "Also, what about that vacation?"

The text is translated like this:

    "Hi, Martin. Nice suit.

    ``Also, what about that vacation?''

Keeping the unsmart quote on the first line. LaTeX will then translate this into an ending quote, which looks strange at the beginning of a line. It should be translated by mmd2tex as:

    ``Hi, Martin. Nice suit.

    ``Also, what about that vacation?''

**Comment by fletcher** [comment]
The first paragraph only has a single double quote, therefore it is not a smart quote (from a computer standpoint, not an English grammar standpoint).  So it is properly left alone.

If this is a construct you use often (I never use it), you could modify MMD to handle it however you desire, or use the double apostrophe syntax manually instead of the lone double quote -- they will be left alone and handled properly by LaTeX (but would not appear correctly in HTML):

    ``Hi, Martin.  Nice suit.

Otherwise, I think this is an edge case that will not be specifically handled by MMD.
