### ISSUE TITLE
GFM newlines

### ISSUE THREAD

**Issue by mikenils** [fletcher/MultiMarkdown-5#51]
Hi! Thank you very much for MultiMarkdown!

Are there any plans to implement GFM newlines in new versions of MMD?

For example, GFM newlines would be very useful for lists like this one:

```
MultiMarkdown general pages:\
- https://github.com/fletcher/MultiMarkdown-5\
- http://fletcherpenney.net/multimarkdown/\
- http://fletcher.github.io/MultiMarkdown-5/

Start-up options:\
http://fletcherpenney.net/multimarkdown/use/

Features:\
http://fletcher.github.io/MultiMarkdown-5/
```

Yes, it may be used backslashes or double-spaces, but since the lists could inlcude 10-20 or more items, it's not very convenient and easy to forgot...

**Comment by fletcher** [comment]
You mean like the feature I implemented about 3 years ago?

http://fletcher.github.io/MultiMarkdown-5/escaped-newlines.html

;)

But if you want to create an *actual* list (e.g. out of the first section), just put a blank line before the list items.

FTP

**Comment by mikenils** [comment]
Hm, I mean pseudo-lists.

So, this markup:

*(Note: there are no backslashes. I removed them)*

```
MultiMarkdown general pages:
https://github.com/fletcher/MultiMarkdown-5
http://fletcherpenney.net/multimarkdown/
http://fletcher.github.io/MultiMarkdown-5/

Start-up options:
http://fletcherpenney.net/multimarkdown/use/

Features:
http://fletcher.github.io/MultiMarkdown-5/
```

Should be rendered as:

![gfm](https://cloud.githubusercontent.com/assets/23511057/21685895/59b2a33e-d374-11e6-9786-cb7d117f1488.PNG)

Currently, in MultiMarkdown there are two ways to create such pseudo-list:

- use double space, *or*
- use backslashes at the end of the lines.

I know about both these methods (and among them, I prefer backslashes), but from my point of view the third method, also known as "GFM newlines" would be even better solution:

```
Hello, my name is Mike. I’m a poet (probably)!

Here is my poem:

Roses are red,
Violets are blue
```

![gfm2](https://cloud.githubusercontent.com/assets/23511057/21686243/c04fa000-d375-11e6-96cd-d096f4fabfda.PNG)

**Comment by fletcher** [comment]
You mean to convert all "naked" newline characters into `<br/>`?

Not gonna happen. That's the exact opposite of one of the key features of Markdown - allowing plain text files to have "semantic" instead of literal meaning. A series of lines of text followed by a blank line is a paragraph. Not a series of individual lines. 

If you want poetry, where line breaks *do* have meaning, then use code blocks and adjust your CSS to get rid of the monospaced font (I did that 10 years ago (via LaTeX instead of HTML) to print a physical book of poetry for a friend using Lulu.com  -- It turned out beautifully! ). If you want lists then use lists (you can always get rid of the bullets if you don't want them, again by changing your CSS).

It seems as though you are attacking your problem from the wrong end, which means fighting against Markdown/MultiMarkdown instead of working with them.  For example, this seems to be a fairly easy problem to solve using CSS, but a difficult problem to solve by modifying MMD to output new HTML.  If I understand correctly, you want to change the appearance of your lists, which means CSS to make the bullets invisible.  If you're changing the *meaning*, that means using different MD/MMD syntax (or creating your own).

**Comment by mikenils** [comment]
Okay, I understand, thanks again! ) I will try to learn new view to this situation!
