### ISSUE TITLE
Switching between ordered and unordered lists in input is not matched in output

### ISSUE THREAD

**Issue by jasedit** [fletcher/MultiMarkdown-5#55]
Given a MultiMarkdown file which contains:
```
1. Item One
2. Item Two

* A different list
```

MultiMarkdown currently produces:
```
<ol>
<li><p>Item One</p></li>
<li><p>Item Two</p></li>
<li><p>A different list</p></li>
</ol>
```

which is unexpected/unintuitive. The only way to switch between list types, non-whitespace characters must be inserted between the two lists. This behavior has apparently been discussed periodically throughout the years (I can find references to this back to [2006](https://www.mail-archive.com/markdown-discuss@six.pairlist.net/msg00071.html) on the markdown mailing list, with no real consensus.

Is this behavior that would be open to a PR to create two lists? Or is this working as intended?

**Comment by fletcher** [comment]
Short answer -- see [this page](https://github.com/fletcher/MultiMarkdown-6/wiki/Note-for-those-with-MMD-5-questions-bugs).

Long answer:

This is definitely a question without a concensus for the "right" answer.  Since list items are allowed to have spaces between them, there is no way to distinguish between one big list and two shorter lists.  Markdown treats your example as a single list, and assumes you mistakenly used the wrong list marker.

CommonMark takes the opposite approach.

MMD 6 uses a completely new parser.  With the new parser, it actually makes sense to adopt the approach used by CommonMark, so (as of now, anyway), this will represent a change in behavior from MMD-5 to MMD-6.

**Comment by jasedit** [comment]
I didn't realize MMD 6 was that far along! I'll have to dig in and check it out.
