### ISSUE TITLE
FODT conversion ignores embedded HTML

### ISSUE THREAD

**Issue by larrykollar** [fletcher/MultiMarkdown-5#56]
Easy way to reproduce:

1.  Insert the following line anywhere in your MMD file:

        <p>This paragraph doesn't appear in the output.</p>

2.  Convert it: `multimarkdown --to=odf test.txt >test.fodt`

3.  Open the output file in LibreOffice. None of the embedded HTML shows up. If you open the file in a text editor, it's not even passed through to the fodt file.

This is important because, while I publish to HTML for production through EPUB, I need a word processor file for editing and beta readers. In more technical (writing) terms, it makes single-sourcing difficult.

**Comment by fletcher** [comment]
Correct.  Because HTML != ODF.  And HTML != LaTeX...  (etc.)

Embedded HTML is ignored when converting to non-HTML formats, because other formats would not "know" what to do with a bunch of raw HTML stuck in the middle.

What is it that you're hoping to accomplish by allowing raw HTML inside an ODF document?  It will (in all likelihood) simply cause the ODF document to not be valid, and to not open in anything other than a text editor.  

If you want to allow raw HTML to be viewed inside other formats, they could be fenced so that they would appear as code blocks in the other formats?  That would mean, of course, that they would be code blocks in HTML as well, though.  

You could use some file transclusion trickery to cause HTML snippets to work normally in HTML files and appear as code blocks in other formats, but this is going to get pretty complicated.

**Comment by larrykollar** [comment]
Your response gave me a hint that led to at least a partial solution: using transclusion with wildcards.

There are a few limitations: using something like `&#8226;` to specify a bullet gets dropped, and using a non-standard style name doesn't get preserved (I had planned to define the style in LibreOffice, whatever).

Thanks for your help, I'll close this.

**Comment by fletcher** [comment]
Non-standard styles would require modifying the MMD source so that they are included.  Not difficult to do, just tedious.

Wildcard transclusion can be quite flexible.  I'm trying to come up with something more flexible for MMD 6:

https://github.com/fletcher/MultiMarkdown-6/issues/38

**Comment by larrykollar** [comment]
Looks promising! I have to admit, though, I'm amused at the emphasis on performance. My test document is a 42,000-word novella exported from Scrivener, roughly 250K. Version 5.4.0 takes less than half a second to process the thing, barely enough to notice a pause, and that's with using wildcard transclusions for section breaks. It's tons faster than Jekyll, I can tell you. ;-)

**Comment by fletcher** [comment]
Yeah....   But when the "competition" is 20-40 times faster, it meant there was room for improvement.  I needed to do a rewrite anyway, and figured I might as well push for the performance in addition to accuracy and new features.  Now you can process your document a 1000x over in a second or two.... ;)  Not sure why you'd want to do that, but you could....  

(It's more that high performance is useful for servers and for MultiMarkdown Composer, not as much for a single document)

**Comment by ickc** [comment]
> It's tons faster than Jekyll, I can tell you. ;-)

I wonder how much of the difference in speed is inherent from the language itself tough. And there's a lot of design choice behind choosing a language, and Jekyll has a very different emphasis (so do GitHub Markdown/pandoc for example).

**Comment by fletcher** [comment]
I am not a world class coder, or formally trained computer scientist.  But it seems that short of hand-rolled assembly, it's tough to beat C in terms of raw power/speed.  MMD v3 was based on peg-markdown, and at the time it was one of the fastest markdown parsers around.  The use of a PEG to define the grammar was still reasonably fast, and gave the added benefit of making the grammar of the language clear.

A few years later, and hand-rolled parsers are kicking the PEG parsers' A$$.  It took me a while to find a system I like, but MMD 6 is lightning fast, but more important to me -- it still allows for a design that can be understood and easily extended.  It's not so "optimized" that it becomes unintelligible to humans.

Plus, I have to admit it was fun to push myself to keep making it faster and faster, despite adding some fairly complex features.  ;)

**Comment by ickc** [comment]
> But it seems that short of hand-rolled assembly, it's tough to beat C in terms of raw power/speed.

Totally agree. there's a tool in https://godbolt.org that can help you to see how your C code will be transformed into assembly, that even if we don't code in assembly, we can still tune our code such that the compiler can be transformed into better assembly code.

There are a few other languages that can get close to C speed (ignoring the close relatives of C): Cython, Julia, Fortran. The later 2 are really mainly for scientific applications only. Personally Cython is very interesting (you can basically write C in Python syntax given a certain rules are followed, but without`#prama`, assembly, etc. kind of low level access).

Pardon me for a beginner's question (never study the MMD C code): does it use an internal AST like pandoc did, and would it be feasible to extend MMD in the way similar to pandoc? (i.e. any format to AST to any other format)

**Comment by fletcher** [comment]
Yes - MultiMarkdown 6 (just like every version since 3) uses an AST structure as part of the transformation process. That allows the same model to easily be translated to HTML, LaTeX, ODF, etc. Each export format is coded in a separate file. 

It's certainly possible to write parsers for reading other formats (e.g. HTML). 

One thing that is different about MultiMarkdown 6 is that for memory and performance reasons, the source text is not copied to the AST, but rather referenced by offset within the source.  This would require some creativity to work around with other document formats but presumably could be done. I haven't needed it myself, but have thought about it if I ever find myself bored. ;)

**Comment by larrykollar** [comment]
There are so many HTML parsers out there that I can't imagine not just using one of those. But I'm lazy like that---I'm no world-class coder, either, and I figure I couldn't do better.

The outliner I maintain (Tines) includes an XML parser from the original coder. I have it on my list to replace it with xmllib sooner or (more likely) much later.

**Comment by ickc** [comment]
Another curious question is, is it parallelized? If not, what are the obstacles on parallelizing it? (sorry for digressing but since this issue was digressing I hope it is fine.)

**Comment by fletcher** [comment]
Is what parallelized?  Do you mean can a single MMD text string be simultaneously processed on multiple threads and then re-joined into a single output string at the end?  No.  What would be the benefit of doing this?  20-25 megabytes of data can be processed on a single thread per second (on my laptop and desktop, both of which are several years old).  The average real world use file is ***MUCH*** smaller than this.  The overhead and complexity of multithreading this would seem to be very low yield, and migh actually worsen performance in most cases, but that's a guess.

**Comment by ickc** [comment]
> migh actually worsen performance in most cases

Right. If there's a lot of small documents, it should be parallelized on the other side (e.g. makefile). From what you said (and didn't say), it seems there's never a complain that a document is too large that MMD will choke on. In that case there's no point of chopping it into smaller chunks.

One place that could have potential trivial parallelization is from transclusion, except that MMD's transclusion behavior prevents this (which have other benefits).

**Comment by fletcher** [comment]
The main problem is running out of memory on your machine.  I routinely test using 100-110 megabyte files that parse in 4-5 seconds.

I posted a bit of information about performance on the README, and plan on expanding a bit on that in the future.  Some of the development process was pretty interesting.

**Comment by fletcher** [comment]
@larrykollar I checked out a video of Tines -- it looks interesting.  The last thing I need is another rabbit hole right now, but the latest text editing engine for MultiMarkdown Composer is written in C, and designed to be cross-platform.  I've often thought it would be handy to be able to run Composer in a terminal session in order to make editing MD/MMD files easier.....  Your video rekindled my interest in doing that sometime....  Darn you!  ;)

**Comment by larrykollar** [comment]
If you ever do it, I'll be glad to beta test it!
